<p>Akademický
senát FEL ÈVUT je nejvy¹¹í samostatný zastupitelský orgán akademické
obce FEL ÈVUT. Rozhoduje o klíèových otázkách chodu fakulty - napøíklad
volí dìkana, schvaluje vnitøní pøedpisy a rozdìlení finanèních
prostøedkù, schvaluje návrh dìkana na jmenování a odvolání èlenù
vìdecké rady.</p>

<p>Senát je v¹ak také tým lidí, kterým zále¾í na
dìní na fakultì, kteøí chtìjí toto dìní aktivnì ovlivòovat, a kteøí
chtìjí neustále zlep¹ovat studijní i pracovní podmínky. Uvítáme proto
jakékoliv obecné i konkrétní pøipomínky, návrhy a podnìty, od studentù
i zamìstnancù FEL.</p>

<p>V¹echna zasedání AS FEL jsou veøejná.</p>