	<!-- Zaèíná senátní menu -->
	<div id='senat-menu'>
		<h1><span>Akademický senát</span></h1>
		<div class="senat-menu-list">
			<a href='/senat'>AKTUÁLNÌ</a>
			| <a href='/senat/onas'>O NÁS</a>
      | <a href='/senat/clenove'>ÈLENOVÉ</a>
			| <a href='/senat/skupiny'>SKUPINY</a>
			| <a href='/senat/zapisy'>ZÁPISY</a>
			| <a href='/senat/dokumenty'>DOKUMENTY</a>
			| <a href='/senat/fotky'>FOTOGALERIE</a>
			| <a href='/senat/archiv'>ARCHIV</a>
			| <a href='/senat/kontakt'>KONTAKT</a>
		</div>
	</div>
	<!-- Konèí senátní menu -->
