	<!-- Zaèíná senátní menu -->
	<div id='senat-menu'>
		<h1><span>Akademický senát</span></h1>
		<div class="senat-menu-list">
			<a href='/senat'>aktuálnì</a>
			| <a href='/senat/onas'>o nás</a>
			| <a href='/senat/zapisy'>zápisy</a>
			| <a href='/senat/dokumenty'>dokumenty</a>
			| <a href='/senat/fotky'>fotogalerie</a>
			| <a href='/senat/archiv'>archiv</a>
			| <a href='/senat/kontakt'>kontakt</a>
			| <a href='/senat/volby'>volby dìkana</a>
		</div>
	</div>
	<!-- Konèí senátní menu -->
