			<div class="aktual">
				<h4><span class="date">/13.&nbsp;7.&nbsp;11/</span>
				<a href="./fotky/110624-volba_dekana"
				>Fotogalerie volby dìkana</a></h4>
				<p>Ve fotogalerii naleznete fotografie z volebního zasedání 
				i dìkanské besedy.</p>
				<hr/>
			</div>
			
			<div class="aktual">
				<h4><span class="date">/23.&nbsp;6.&nbsp;11/</span>
				AS FEL zvolil kandidáta na dìkana</h4>
				<p>Akademický senát zvolil kandidátem na dìkana
				prof.Ing.&nbsp;Pavla Ripku,&nbsp;CSc. Dìkujeme v¹em tøem
				uchazeèùm za jejich pøínos do&nbsp;pøedvolební diskuze
				i&nbsp;odvahu pøedstavit svoji vizi pro FEL.
				Èerstvì zvolenému dìkanovi pøejeme hodnì úspìchù
				v&nbsp;jeho nové funkci.</p>
				<hr/>
			</div>
			
			<div class="aktual">
				<h4><span class="date">/23.&nbsp;6.&nbsp;11/ </span>
				<a href='https://media.fel.cvut.cz/archive/asfel/20110622-diskuze.mp3'
				>Audiozáznam z dìkanské besedy</a></h4>
				<p>Audiozáznam z vèerej¹í debaty s&nbsp;kandidáty na dìkana je
				k&nbsp;dispozici ke&nbsp;sta¾ení.</p>
				<hr/>
			</div>

			<!--
			<div class="aktual">
				<h4><span class="date">/20.&nbsp;6.&nbsp;11/ </span>
				Beseda s kandidáty na dìkana ji¾ tuto støedu</h4>
				<p>Dne 22.6. se v místnosti T2:D3-309 od 14:00 uskuteèní
				veøejná beseda s kandidáty na dìkana. Akademická obec se mù¾e
				ptát a debatovat s mo¾ným budoucím dìkanem FEL:
				prof. Pavlem Ripkou,
				prof. Lambertem Spaanenburgem a
				prof. Borisem ©imákem. Besedou
				bude provázet prof. Václav Hlaváè.</p>
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/15.&nbsp;6.&nbsp;11/ </span>
				<a href="volby">Kandidáti na dìkana</a></h4>
				<p>Volební komise AS FEL pøijala pøihlá¹ky tøí uchazeèù
				o&nbsp;kandidaturu na dìkana: prof. Ing. Pavla Ripky, CSc,
				prof. Dr.Ir. Lamberta Spaanenburga a
				prof. Ing. Borise ©imáka, CSc.
				Jejich volební programy a ¾ivotopisy jsou zveøejnìné na
				<a href='http://www.fel.cvut.cz/senat/volby/'>stránce voleb</a>.</p>
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/11.&nbsp;4.&nbsp;11/ </span>
				<a href="volby">Vyhlá¹ení druhého kola voleb dìkana</a></h4>
				<p>Termín pro odevzdání kandidátek je stanoven
				na 14.&nbsp;6.&nbsp;2011 12.00,
				volba kandidáta na dìkana probìhne 24.&nbsp;6.&nbsp;2011.</p>
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/1.&nbsp;4.&nbsp;11/</span>
				První volba dìkana</h4>
				<p>V první volbì dne 1.&nbsp;4. AS FEL nezvolil dìkana.
				Dìkujeme v¹em kandidátùm za jejich èas, snahu i podnìty
				do debaty o budoucnosti FEL.</p> 
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/28.&nbsp;3.&nbsp;11/ </span>
				<a href="https://media.feld.cvut.cz/archive/asfel/20110323-diskuze.mp3"
				>Záznam besedy s&nbsp;kandidáty na&nbsp;dìkana</a></h4>
				<p>Audiozáznam besedy akademické obce s&nbsp;kandidáty na&nbsp;dìkana,
				která probìhla 23.&nbsp;3.&nbsp;2011, je nyní k&nbsp;dispozici
				<a href="https://media.feld.cvut.cz/archive/asfel/20110323-diskuze.mp3"
				>ke sta¾ení</a>.</p>
				<p>Záznam pøedstavení kandidátù akademické obci
				(ze dne 18.&nbsp;3.&nbsp;2011) je souèástí
				<a href="https://media.feld.cvut.cz/archive/asfel/20110318.mp3"
				>audiozáznamu 10.&nbsp;øádného zasedání AS&nbsp;FEL</a>.</p> 
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/9.&nbsp;3.&nbsp;11/ </span>
				<a href="volby">Prùbìh voleb</a></h4>
				<p>Pøedstavení kandidátù na&nbsp;dìkana probìhne na&nbsp;pøí¹tím zasedání
				AS FEL. Beseda kandidátù s&nbsp;akademickou obcí se vyhla¹uje
				na&nbsp;23.&nbsp;3.&nbsp;2011.</p>
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/9.&nbsp;3.&nbsp;11/ </span>
				<a href="volby">Kandidáti na dìkana</a></h4>
				<p>Akademický senát obdr¾el dva dìkanské projekty
				kandidátù na dìkana.</p>
				<hr/>
			</div>

			<div class="aktual">
				<h4><span class="date">/2.&nbsp;2.&nbsp;11/ </span>
				<a href="volby">Vyhla¹ujeme volby dìkana</a></h4>
				<p>Termín pro odevzdání kandidátek je stanoven
				na 9.&nbsp;3.&nbsp;2011 12.00,
				volba kandidáta na dìkana probìhne 1.&nbsp;4.&nbsp;2011.</p>
				<hr/>
			</div>-->
