<p>Pøí¹tí øádné zasedání AS FEL se bude konat
<b>23.&nbsp;3.&nbsp;2012 od&nbsp;9:00</b>
v&nbsp;místnosti&nbsp;C4-80.</p>

<!--
<h4>Návrh programu:</h4>
<ol id='program'>
<li>Schválení programu 19. øádného zasedání</li>
<li>Volba pøedsedajícího a tajemníka AS FEL</li>
<li>Schválení zápisu z 18. øádného zasedání AS FEL</li>
<li>Zpráva ze zasedání komise pro rozvoj (CIIK)</li>
<li>Schválení Statutu a Organizaèního øádu FEL (nutná nadpolovièní vìt¹ina v¹ech senátorù, tzn. alespoò 14 hlasù pro)</li>
<li>Èasový plán akademického roku 2012/2013</li>
<li>Aktualizace dlouhodobého zámìru ÈVUT FEL pro rok 2012</li>
<li>Metodika pro stanovení pedagogického výkonu kateder</li>
<li>Metodika úhrady za vyu¾ívání místností na FEL ÈVUT</li>
<li>Rùzné<ol>
<li>Prezentace FEL - samolepky</li>
</ol></li>
<li>Termín dal¹ího zasedání</li>
</ol>-->

<h4>Související:</h4><ul>
<!--<li><a href="https://felnet.feld.cvut.cz/infodek/SENAT/PREDKLADANO/">-->
<li><a href="https://felnet.feld.cvut.cz/infodek/SENAT/VEDENI/FUNKCNI%20OBDOBI%20AS%202010-13/">
Pøedkládané materiály</a></li>
</ul>

